import type { ApiEndpointItem } from '../types';
import { buildRawUtilityUrl, buildRouteUrl } from '../url';

export function buildSystemCatalog(base: URL): ApiEndpointItem[] {
  return [
    {
      id: 'persona-contract-full',
      category: 'System',
      method: 'GET',
      name: 'Persona Contract',
      description: 'Fetch canonical full persona contract (single source of truth)',
      url: buildRouteUrl(base, 'persona-contract', { token: '{TOKEN}', format: 'text' }),
    },
    {
      id: 'persona-contract-json',
      category: 'System',
      method: 'GET',
      name: 'Persona Contract (JSON)',
      description: 'Fetch active persona contract as JSON envelope',
      url: buildRouteUrl(base, 'persona-contract', { token: '{TOKEN}' }),
    },
    {
      id: 'persona-contract-history',
      category: 'System',
      method: 'GET',
      name: 'Persona Contract History',
      description: 'Read version history of persona contract (admin only)',
      url: buildRouteUrl(base, 'persona-contract', { token: '{TOKEN}', action: 'history', limit: '{LIMIT}' }),
    },
    {
      id: 'persona-contract-save',
      category: 'System',
      method: 'POST',
      name: 'Persona Contract Save',
      description: 'Save a new active contract version (admin only)',
      url: buildRouteUrl(base, 'persona-contract', { token: '{TOKEN}', action: 'save' }),
      body: '{ "text": "FULL CONTRACT...", "change_note": "Kurzbeschreibung", "version": "optional" }',
    },
    {
      id: 'persona-contract-restore',
      category: 'System',
      method: 'POST',
      name: 'Persona Contract Restore',
      description: 'Restore one historical contract as new active version (admin only)',
      url: buildRouteUrl(base, 'persona-contract', { token: '{TOKEN}', action: 'restore' }),
      body: '{ "version_id": 12, "change_note": "Restore Grund" }',
    },
    {
      id: 'api-install',
      category: 'System',
      method: 'GET',
      name: 'Install',
      description: 'Initialize database and seed data',
      url: buildRawUtilityUrl(base, 'install'),
    },
    {
      id: 'api-test',
      category: 'System',
      method: 'GET',
      name: 'Test',
      description: 'Run API/DB connection check',
      url: buildRawUtilityUrl(base, 'test'),
    },
    {
      id: 'api-db-tables',
      category: 'System',
      method: 'GET',
      name: 'DB Tables',
      description: 'Read-only list of SQLite tables with row counts (admin only)',
      url: buildRouteUrl(base, 'db', { token: '{TOKEN}', action: 'tables' }),
    },
    {
      id: 'api-db-schema',
      category: 'System',
      method: 'GET',
      name: 'DB Schema',
      description: 'Read-only table schema (admin only)',
      url: buildRouteUrl(base, 'db', { token: '{TOKEN}', action: 'schema', table: '{TABLE}' }),
    },
    {
      id: 'api-db-rows',
      category: 'System',
      method: 'GET',
      name: 'DB Rows',
      description: 'Read-only table rows with pagination (admin only)',
      url: buildRouteUrl(base, 'db', {
        token: '{TOKEN}',
        action: 'rows',
        table: '{TABLE}',
        limit: '{LIMIT}',
        offset: '{OFFSET}',
      }),
    },
    {
      id: 'api-health',
      category: 'System',
      method: 'GET',
      name: 'Health',
      description: 'Service and DB liveness check',
      url: buildRouteUrl(base, 'health'),
    },
    {
      id: 'api-stats',
      category: 'System',
      method: 'GET',
      name: 'Stats',
      description: 'Operational metrics and task counters',
      url: buildRouteUrl(base, 'stats', { token: '{TOKEN}' }),
    },
    {
      id: 'api-reset',
      category: 'System',
      method: 'GET',
      name: 'Reset',
      description: 'Reset the database (admin only)',
      url: `${buildRawUtilityUrl(base, 'reset')}?token={TOKEN}`,
    },
  ];
}
