import type { ApiEndpointItem } from '../types';
import { buildRouteUrl } from '../url';

export function buildTasksCatalog(base: URL): ApiEndpointItem[] {
  return [
    {
      id: 'tasks-list',
      category: 'Tasks',
      method: 'GET',
      name: 'Tasks',
      description: 'Get active (not deleted) tasks',
      url: buildRouteUrl(base, 'tasks', { token: '{TOKEN}' }),
    },
    {
      id: 'tasks-with-deleted',
      category: 'Tasks',
      method: 'GET',
      name: 'Tasks incl. Deleted',
      description: 'Get active + soft-deleted tasks',
      url: buildRouteUrl(base, 'tasks', { token: '{TOKEN}', include_deleted: '1' }),
    },
    {
      id: 'tasks-single',
      category: 'Tasks',
      method: 'GET',
      name: 'Task by ID',
      description: 'Get one ticket by ID',
      url: buildRouteUrl(base, 'tasks/{ID}', { token: '{TOKEN}' }),
    },
    {
      id: 'tasks-filtered',
      category: 'Tasks',
      method: 'GET',
      name: 'Tasks by Assignee',
      description: 'Get tasks for one assignee',
      url: buildRouteUrl(base, 'tasks', { token: '{TOKEN}', assignee: '{NAME}' }),
    },
    {
      id: 'tasks-history',
      category: 'Tasks',
      method: 'GET',
      name: 'Task History',
      description: 'Get event timeline for one task',
      url: buildRouteUrl(base, 'tasks', { action: 'history', token: '{TOKEN}', task_id: '{ID}' }),
    },
    {
      id: 'tasks-add',
      category: 'Tasks',
      method: 'POST',
      name: 'Add Task',
      description: 'Create a new task',
      url: buildRouteUrl(base, 'tasks', { action: 'add', token: '{TOKEN}' }),
      body: '{ "title": "...", "description": "...", "tags": "backend, urgent", "depends_on": [3,5], "assignee": "...", "status": "open|in_progress|blocked|ready_for_review|done", "priority": "low|normal|high|urgent" }',
    },
    {
      id: 'tasks-update',
      category: 'Tasks',
      method: 'POST',
      name: 'Update Task',
      description: 'Update one or more ticket fields (requires updated_at, returns 409 on conflict)',
      url: buildRouteUrl(base, 'tasks', { action: 'update', token: '{TOKEN}' }),
      body: '{ "task_id": 1, "updated_at": "2026-03-13 12:45:00", "title": "...", "description": "...", "tags": "bug,api", "depends_on": [3], "assignee": "...", "status": "open|in_progress|blocked|ready_for_review|done", "priority": "low|normal|high|urgent" }',
    },
    {
      id: 'tasks-claim',
      category: 'Tasks',
      method: 'POST',
      name: 'Claim Task',
      description: 'Claim ownership lock (blocked with 409 if dependencies are not done)',
      url: buildRouteUrl(base, 'tasks', { action: 'claim', token: '{TOKEN}' }),
      body: '{ "task_id": 1 }',
    },
    {
      id: 'tasks-route-suggest',
      category: 'Tasks',
      method: 'GET',
      name: 'Route Suggest',
      description: 'Server-side assignee/status recommendation by tags, skills, dependencies and lock state',
      url: buildRouteUrl(base, 'tasks', { action: 'route_suggest', token: '{TOKEN}', task_id: '{ID}' }),
    },
    {
      id: 'tasks-route-suggest-all',
      category: 'Tasks',
      method: 'GET',
      name: 'Route Suggest (All Tasks)',
      description: 'Server-side routing suggestions for all active tasks',
      url: buildRouteUrl(base, 'tasks', { action: 'route_suggest', token: '{TOKEN}' }),
    },
    {
      id: 'tasks-route-apply',
      category: 'Tasks',
      method: 'POST',
      name: 'Route Apply',
      description: 'Apply server route recommendation to one task (admin only, requires updated_at)',
      url: buildRouteUrl(base, 'tasks', { action: 'route_apply', token: '{TOKEN}' }),
      body: '{ "task_id": 1, "updated_at": "2026-03-16 12:30:00" }',
    },
    {
      id: 'tasks-release',
      category: 'Tasks',
      method: 'POST',
      name: 'Release Task',
      description: 'Release ownership lock (lock owner or admin); default status=open, optional blocked',
      url: buildRouteUrl(base, 'tasks', { action: 'release', token: '{TOKEN}' }),
      body: '{ "task_id": 1, "status": "open|blocked", "note": "optional" }',
    },
    {
      id: 'tasks-request-review',
      category: 'Tasks',
      method: 'POST',
      name: 'Request Review',
      description: 'Move ticket to ready_for_review (requires updated_at)',
      url: buildRouteUrl(base, 'tasks', { action: 'request_review', token: '{TOKEN}' }),
      body: '{ "task_id": 1, "updated_at": "2026-03-13 12:45:00" }',
    },
    {
      id: 'tasks-approve',
      category: 'Tasks',
      method: 'POST',
      name: 'Approve Ticket',
      description: 'Approve ready_for_review ticket and mark done (admin only, requires updated_at)',
      url: buildRouteUrl(base, 'tasks', { action: 'approve', token: '{TOKEN}' }),
      body: '{ "task_id": 1, "updated_at": "2026-03-13 12:45:00" }',
    },
    {
      id: 'tasks-delete',
      category: 'Tasks',
      method: 'POST',
      name: 'Delete Task',
      description: 'Soft-delete a task (sets deleted_at)',
      url: buildRouteUrl(base, 'tasks', { action: 'delete', token: '{TOKEN}' }),
      body: '{ "task_id": 1 }',
    },
    {
      id: 'tasks-restore',
      category: 'Tasks',
      method: 'POST',
      name: 'Restore Task',
      description: 'Restore a soft-deleted task',
      url: buildRouteUrl(base, 'tasks', { action: 'restore', token: '{TOKEN}' }),
      body: '{ "task_id": 1 }',
    },
  ];
}
